
branches:
  only:
  - master
  - gh-pages

notifications:
  email:
    recipients:
      - d.p.carlisle@gmail.com
      
before_install:
  - sudo apt-get install -y rxp

install:
 - ./build/install-tools

cache:
  directories:
    - /tmp/jars
    - /tmp/texlive

script:
 - ./build/run-restyle

